import { describe, expect, it } from "vitest";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import {
  applyPlan,
  emptyManifest,
  planInstall,
  pruneStaleFiles,
  readManifest,
  uninstallFiles,
} from "../src/install/engine.js";
import type { FileCandidate } from "../src/install/plan.js";
import { readIfExists, resolveWithin } from "../src/util/fs.js";

function tmpRoot(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "steward-engine-"));
}

const candidates: FileCandidate[] = [
  {
    file: ".vibe/skills/vibe.md",
    content: "Generated by Steward v0.1.0\nvibe skill",
    target: "core",
  },
  {
    file: ".claude/commands/vibe.md",
    content: "Generated by Steward v0.1.0\nclaude stub",
    target: "claude",
  },
  {
    file: "AGENTS.md",
    content: "user intro\n<!-- steward:begin:skills-index v0.1.0 -->\nindex\n<!-- steward:end:skills-index -->\n",
    target: "codex",
    mode: "block",
    blockId: "skills-index",
  },
];

describe("install engine", () => {
  it("plans, applies, and records a manifest", () => {
    const root = tmpRoot();
    const plan = planInstall(root, candidates, { updateManaged: true });
    expect(plan.map((a) => a.kind)).toEqual(["create", "create", "create"]);

    const manifest = emptyManifest();
    const result = applyPlan(root, plan, manifest);
    expect(result.applied).toHaveLength(3);
    expect(result.blocked).toHaveLength(0);
    expect(result.backupDir).toBeNull();

    const stored = readManifest(root)!;
    expect(stored.schema).toBe("steward.manifest.v1");
    expect(stored.files).toHaveLength(3);
    expect(stored.files.map((f) => f.target)).toEqual(["core", "claude", "codex"]);
    expect(readIfExists(resolveWithin(root, ".vibe/skills/vibe.md"))).toContain("vibe skill");
    // block merge preserves "user intro" (candidate already contains it)
    expect(readIfExists(resolveWithin(root, "AGENTS.md"))).toContain("user intro");
  });

  it("is idempotent: a second run skips everything", () => {
    const root = tmpRoot();
    const manifest = emptyManifest();
    applyPlan(root, planInstall(root, candidates, { updateManaged: true }), manifest);
    const plan2 = planInstall(root, candidates, { updateManaged: true });
    expect(plan2.every((a) => a.kind === "skip")).toBe(true);
  });

  it("backs up and regenerates changed managed files", () => {
    const root = tmpRoot();
    const manifest = emptyManifest();
    applyPlan(root, planInstall(root, candidates, { updateManaged: true }), manifest);

    const target = resolveWithin(root, ".claude/commands/vibe.md");
    fs.writeFileSync(target, "Generated by Steward v0.1.0\nlocally patched", "utf8");

    const plan2 = planInstall(root, candidates, { updateManaged: true });
    const result = applyPlan(root, plan2, manifest);
    expect(result.applied).toHaveLength(1);
    expect(result.backupDir).not.toBeNull();
    expect(readIfExists(target)).toContain("claude stub");
    // the backup exists under .vibe/install/backups/<stamp>/...
    const backups = fs.readdirSync(path.join(root, ".vibe", "install", "backups"));
    expect(backups.length).toBe(1);
  });

  it("never applies blocked (foreign) actions", () => {
    const root = tmpRoot();
    const foreignFile = resolveWithin(root, ".claude/commands/vibe.md");
    fs.mkdirSync(path.dirname(foreignFile), { recursive: true });
    fs.writeFileSync(foreignFile, "user content", "utf8");
    const plan = planInstall(root, candidates, { updateManaged: true });
    const foreign = plan.find((a) => a.file === ".claude/commands/vibe.md")!;
    expect(foreign.risk).toBe("requires-confirmation");

    const manifest = emptyManifest();
    const result = applyPlan(root, plan, manifest);
    expect(result.blocked.map((a) => a.file)).toContain(".claude/commands/vibe.md");
    expect(readIfExists(resolveWithin(root, ".claude/commands/vibe.md"))).toBe("user content");
  });

  it("uninstall removes managed files but preserves user-modified ones", () => {
    const root = tmpRoot();
    const manifest = emptyManifest();
    applyPlan(root, planInstall(root, candidates, { updateManaged: true }), manifest);

    // user edits one managed file after install
    fs.writeFileSync(
      resolveWithin(root, ".claude/commands/vibe.md"),
      "user customized this",
      "utf8"
    );

    const stored = readManifest(root)!;
    const result = uninstallFiles(root, stored);
    expect(result.removed).toContain(".vibe/skills/vibe.md");
    expect(result.kept.map((k) => k.file)).toContain(".claude/commands/vibe.md");
    expect(fs.existsSync(resolveWithin(root, ".claude/commands/vibe.md"))).toBe(true);
  });

  it("uninstall strips managed blocks and keeps the host doc", () => {
    const root = tmpRoot();
    const manifest = emptyManifest();
    applyPlan(root, planInstall(root, candidates, { updateManaged: true }), manifest);
    const stored = readManifest(root)!;
    const result = uninstallFiles(root, stored);
    expect(result.stripped).toContain("AGENTS.md");
    const after = readIfExists(resolveWithin(root, "AGENTS.md"));
    expect(after).toContain("user intro");
    expect(after).not.toContain("steward:begin");
  });

  it("uninstall dry-run deletes nothing", () => {
    const root = tmpRoot();
    const manifest = emptyManifest();
    applyPlan(root, planInstall(root, candidates, { updateManaged: true }), manifest);
    const stored = readManifest(root)!;
    const result = uninstallFiles(root, stored, { dryRun: true });
    expect(result.removed.length + result.stripped.length).toBe(3);
    expect(fs.existsSync(resolveWithin(root, ".vibe/skills/vibe.md"))).toBe(true);
  });

  it("prunes stale manifest entries that are no longer planned", () => {
    const root = tmpRoot();
    const manifest = emptyManifest();
    applyPlan(root, planInstall(root, candidates, { updateManaged: true }), manifest);
    const stored = readManifest(root)!;

    // new plan drops the claude artifact entirely
    const plannedFiles = new Set([".vibe/skills/vibe.md", "AGENTS.md"]);
    const pruned = pruneStaleFiles(root, stored, plannedFiles);
    expect(pruned.removed).toContain(".claude/commands/vibe.md");
    expect(stored.files.map((f) => f.file).sort()).toEqual([".vibe/skills/vibe.md", "AGENTS.md"]);
    expect(fs.existsSync(resolveWithin(root, ".claude/commands/vibe.md"))).toBe(false);
  });

  it("prune keeps user-modified stale files", () => {
    const root = tmpRoot();
    const manifest = emptyManifest();
    applyPlan(root, planInstall(root, candidates, { updateManaged: true }), manifest);
    const stored = readManifest(root)!;
    fs.writeFileSync(
      resolveWithin(root, ".claude/commands/vibe.md"),
      "user customized this",
      "utf8"
    );
    const pruned = pruneStaleFiles(root, stored, new Set([".vibe/skills/vibe.md"]));
    expect(pruned.removed).not.toContain(".claude/commands/vibe.md");
    expect(pruned.kept.map((k) => k.file)).toContain(".claude/commands/vibe.md");
  });
});
