import { describe, expect, it } from "vitest";
import { classifyFile, type FileCandidate, type PlanOptions } from "../src/install/plan.js";

const opts: PlanOptions = { updateManaged: true };

const candidate: FileCandidate = {
  file: ".claude/commands/vibe.md",
  content: "Generated by Steward v0.1.0\nbody",
  target: "claude",
};

describe("classifyFile", () => {
  it("creates when the file does not exist", () => {
    const action = classifyFile(candidate, null, opts);
    expect(action.kind).toBe("create");
    expect(action.risk).toBe("safe");
    expect(action.ownership).toBe("managed");
  });

  it("skips when content is identical", () => {
    const action = classifyFile(candidate, candidate.content, opts);
    expect(action.kind).toBe("skip");
  });

  it("overwrites managed files when updateManaged is on", () => {
    const action = classifyFile(candidate, "Generated by Steward v0.0.1\nold", opts);
    expect(action.kind).toBe("overwrite");
    expect(action.ownership).toBe("managed");
    expect(action.risk).toBe("safe");
  });

  it("skips managed updates when updateManaged is off", () => {
    const action = classifyFile(
      candidate,
      "Generated by Steward v0.0.1\nold",
      { updateManaged: false }
    );
    expect(action.kind).toBe("skip");
  });

  it("blocks foreign files instead of overwriting them", () => {
    const action = classifyFile(candidate, "user wrote this", opts);
    expect(action.kind).toBe("skip");
    expect(action.risk).toBe("requires-confirmation");
    expect(action.ownership).toBe("foreign");
    expect(action.reason).toMatch(/refusing to overwrite/);
  });

  it("overwrites foreign files only with explicit authorization", () => {
    const action = classifyFile(candidate, "user wrote this", {
      ...opts,
      allowForeignOverwrite: true,
    });
    expect(action.kind).toBe("overwrite");
    expect(action.risk).toBe("requires-confirmation");
  });

  it("treats block-mode candidates as safe additive merges", () => {
    const block: FileCandidate = {
      file: "AGENTS.md",
      content: "user intro\n<!-- steward:begin:skills-index v0.1.0 -->\nindex\n<!-- steward:end:skills-index -->\n",
      target: "codex",
      mode: "block",
      blockId: "skills-index",
    };
    const action = classifyFile(block, "user intro\n", opts);
    expect(action.kind).toBe("overwrite");
    expect(action.risk).toBe("safe");
    expect(action.mode).toBe("block");
  });

  it("normalizes path separators in the action file name", () => {
    const action = classifyFile({ ...candidate, file: ".claude\\commands\\vibe.md" }, null, opts);
    expect(action.file).toBe(".claude/commands/vibe.md");
  });
});
