export const VERSION = "0.1.0";

export const PRODUCT_NAME = "Steward";

/** Marker prefix used in every generated file and managed block. */
export const MANAGED_BY = `Generated by Steward v${VERSION}`;
