import { describe, expect, it } from "vitest";
import { parseSkill } from "@steward/core";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { ADAPTERS, detectAll, getAdapter, isAdapterId } from "../src/registry.js";
import { commandStub, memoryIndexMarkdown } from "../src/shared.js";

const SKILLS_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../../skills"
);

function skillOf(id: string) {
  const file = path.join(SKILLS_DIR, `${id}.md`);
  return parseSkill(fs.readFileSync(file, "utf8"), `skills/${id}.md`);
}

const vibe = skillOf("vibe");
const ship = skillOf("ship");

describe("registry", () => {
  it("exposes the full first-class adapter set", () => {
    expect(ADAPTERS.map((a) => a.id)).toEqual([
      "claude",
      "codex",
      "cursor",
      "opencode",
      "gemini",
      "windsurf",
      "cline",
      "roo",
      "copilot",
      "aider",
    ]);
  });

  it("resolves adapters by id and rejects unknown ids", () => {
    expect(getAdapter("claude").id).toBe("claude");
    expect(isAdapterId("aider")).toBe(true);
    expect(isAdapterId("emacs")).toBe(false);
    expect(() => getAdapter("emacs" as never)).toThrow(/unknown target/);
  });

  it("keeps confidence claims honest", () => {
    for (const a of ADAPTERS) {
      expect(["verified", "partial", "unverified"]).toContain(a.capabilities.confidence);
    }
  });
});

describe("per-adapter artifacts", () => {
  it("claude emits a command stub and a native skill", () => {
    const artifacts = getAdapter("claude").artifacts(vibe);
    expect(artifacts.map((a) => a.file).sort()).toEqual([
      ".claude/commands/vibe.md",
      ".claude/skills/vibe/SKILL.md",
    ]);
    for (const a of artifacts) {
      expect(a.content).toContain(".vibe/skills/vibe.md");
      expect(a.content).toContain("Generated by Steward");
    }
  });

  it("gemini emits valid TOML command files", () => {
    const artifacts = getAdapter("gemini").artifacts(vibe);
    const toml = artifacts[0];
    expect(toml.file).toBe(".gemini/commands/vibe.toml");
    expect(toml.content).toMatch(/^description = "/);
    expect(toml.content).toContain("'''");
  });

  it("codex/opencode share AGENTS.md block id; copilot/aider use their own docs", () => {
    const codex = getAdapter("codex").indexBlock([vibe])!;
    const opencode = getAdapter("opencode").indexBlock([vibe])!;
    expect(codex.blockId).toBe("skills-index");
    expect(codex.file).toBe("AGENTS.md");
    expect(opencode.file).toBe("AGENTS.md");
    const copilot = getAdapter("copilot").indexBlock([vibe])!;
    const aider = getAdapter("aider").indexBlock([vibe])!;
    expect(copilot.file).toBe(".github/copilot-instructions.md");
    expect(aider.file).toBe("CONVENTIONS.md");
  });

  it("memory-doc-only adapters emit no per-skill artifacts", () => {
    expect(getAdapter("copilot").artifacts(vibe)).toEqual([]);
    expect(getAdapter("aider").artifacts(ship)).toEqual([]);
  });

  it("rule-file adapters emit one rule per skill", () => {
    for (const id of ["windsurf", "cline", "roo"] as const) {
      const adapter = getAdapter(id);
      const artifacts = adapter.artifacts(vibe);
      expect(artifacts).toHaveLength(1);
      expect(artifacts[0].file).toContain(`steward-vibe`);
      expect(artifacts[0].content).toContain(".vibe/skills/vibe.md");
    }
  });
});

describe("detection", () => {
  it("detects nothing in an empty project", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "steward-detect-"));
    for (const d of detectAll(root)) {
      expect(d.detected).toBe(false);
    }
  });

  it("detects harness signals from marker files", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "steward-detect-"));
    fs.mkdirSync(path.join(root, ".claude"));
    fs.mkdirSync(path.join(root, ".github"), { recursive: true });
    fs.writeFileSync(path.join(root, ".github", "copilot-instructions.md"), "x");
    fs.writeFileSync(path.join(root, "CONVENTIONS.md"), "x");

    const byId = new Map(detectAll(root).map((d) => [d.id, d]));
    expect(byId.get("claude")!.detected).toBe(true);
    expect(byId.get("copilot")!.detected).toBe(true);
    expect(byId.get("aider")!.detected).toBe(true);
    expect(byId.get("cursor")!.detected).toBe(false);
  });
});

describe("shared serialization", () => {
  it("commandStub escapes quotes for YAML scalars", () => {
    const skill = {
      ...vibe,
      front: { ...vibe.front, description: 'Uses "quoted" terms' },
    };
    const stub = commandStub(skill);
    expect(stub.front).toContain('description: "Uses \\"quoted\\" terms"');
  });

  it("memoryIndexMarkdown lists every skill with risk", () => {
    const md = memoryIndexMarkdown([vibe, ship], "Test");
    expect(md).toContain("| vibe | medium |");
    expect(md).toContain("| ship | critical |");
    expect(md).toContain(".vibe/skills/");
  });
});
