import {
  listBuiltinSkills,
  VERSION,
  type CanonicalSkill,
} from "@steward/core";

/**
 * Claude Code plugin + marketplace generation.
 *
 * Steward's normal install path writes thin per-project pointers into the
 * user's project (.claude/skills/...). A marketplace plugin is different: it
 * ships to any project via the plugin cache, so artifacts must be
 * SELF-CONTAINED — command and skill bodies embed the canonical skill text
 * instead of pointing at `.vibe/skills/`.
 *
 * Everything here is a deterministic transform of the canonical skill library,
 * so the committed plugin tree can be regenerated byte-for-byte
 * (`bun run plugin:check` in CI enforces this).
 */

export const MARKETPLACE_RELATIVE_DIR = ".claude-plugin";
export const MARKETPLACE_FILE = `${MARKETPLACE_RELATIVE_DIR}/marketplace.json`;
export const PLUGIN_DIR = "plugins/steward";
export const PLUGIN_NAME = "steward";

export interface GeneratedFile {
  /** Repo-root-relative path. */
  file: string;
  content: string;
}

function pluginSkillBody(skill: CanonicalSkill): string {
  return [
    `# Steward — ${skill.front.title}`,
    "",
    `> Canonical Steward skill \`${skill.front.id}\` v${skill.front.version}.`,
    `> ${skill.front.description}`,
    "",
    skill.body.trimEnd(),
    "",
    "---",
    "",
    "Apply this process exactly. Do not claim completion without the evidence this skill requires.",
    "Lifecycle state is deterministic: inspect with `steward status`, prove completion with `steward verify <feature>` — prose cannot change lifecycle state; only executed, recorded evidence can.",
    "",
  ].join("\n");
}

function pluginCommandBody(skill: CanonicalSkill): string {
  const lines = [
    `Read and follow the Steward skill '${skill.front.id}' (v${skill.front.version}, "${skill.front.title}").`,
    "",
    ...pluginSkillBody(skill).split("\n").slice(4), // strip the H1 + pointer block; command already names the skill
    "",
    "Skill arguments: $ARGUMENTS",
    "",
  ];
  return lines.join("\n");
}

export function marketplaceJson(): string {
  const manifest = {
    name: "steward",
    description:
      "Steward — the engineering operating system for AI coding agents. Evidence over claims: IDEA → SPEC → PLAN → IMPLEMENT → TEST → VERIFY → COMPLETE, with deterministic state, Guardian checks, security review, and engineering memory.",
    owner: {
      name: "Tamheed Nazir",
      url: "https://github.com/IamTamheedNazir/DevPilotPro",
    },
    plugins: [
      {
        name: PLUGIN_NAME,
        source: `./${PLUGIN_DIR}`,
        description:
          "14 evidence-gated engineering workflow skills (vibe, spec, plan, build, test, verify, debug, security, qa, review, docs, ship, research, architecture) with deterministic completion gates.",
        version: VERSION,
        author: {
          name: "Tamheed Nazir",
          url: "https://github.com/IamTamheedNazir/DevPilotPro",
        },
        homepage: "https://github.com/IamTamheedNazir/DevPilotPro",
        repository: "https://github.com/IamTamheedNazir/DevPilotPro",
        license: "MIT",
        keywords: ["engineering", "workflow", "evidence", "agents", "skills"],
      },
    ],
  };
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

export function pluginJson(): string {
  const manifest = {
    name: PLUGIN_NAME,
    description:
      "Steward engineering operating system: evidence-gated workflows (spec → plan → build → verify → ship) with deterministic completion gates and engineering memory.",
    version: VERSION,
    author: {
      name: "Tamheed Nazir",
      url: "https://github.com/IamTamheedNazir/DevPilotPro",
    },
    homepage: "https://github.com/IamTamheedNazir/DevPilotPro",
    repository: "https://github.com/IamTamheedNazir/DevPilotPro",
    license: "MIT",
    keywords: ["engineering", "workflow", "evidence", "agents", "skills"],
  };
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

/** All marketplace/plugin files, derived purely from the canonical skills. */
export function generateClaudePlugin(): GeneratedFile[] {
  const skills = listBuiltinSkills();
  if (skills.length === 0) {
    throw new Error("no canonical skills found — refusing to generate an empty plugin");
  }

  const files: GeneratedFile[] = [
    { file: MARKETPLACE_FILE, content: marketplaceJson() },
    { file: `${PLUGIN_DIR}/.claude-plugin/plugin.json`, content: pluginJson() },
  ];

  for (const skill of skills) {
    files.push({
      file: `${PLUGIN_DIR}/commands/${skill.front.id}.md`,
      content: [
        "---",
        `description: ${JSON.stringify(skill.front.description)}`,
        "---",
        "",
        pluginCommandBody(skill),
      ].join("\n"),
    });
    files.push({
      file: `${PLUGIN_DIR}/skills/${skill.front.id}/SKILL.md`,
      content: [
        "---",
        `name: ${skill.front.id}`,
        `description: ${JSON.stringify(skill.front.description)}`,
        "---",
        "",
        pluginSkillBody(skill),
      ].join("\n"),
    });
  }

  return files;
}
