import * as path from "node:path";

/**
 * Which layer of the install owns a file. "core" is the canonical library
 * under .vibe/; every other value is a harness adapter id. The set of
 * adapter ids lives in @steward/adapters — the core domain model stays
 * vendor-neutral by design.
 */
export type InstallTarget = "core" | (string & {});

export type FileActionKind = "create" | "overwrite" | "delete" | "skip";

export interface FileAction {
  kind: FileActionKind;
  /** Path relative to the project root, POSIX separators. */
  file: string;
  content?: string;
  /** Why this action was chosen (dry-run output and audit trail). */
  reason: string;
  /** "managed" files are Steward-generated; "foreign" files are not. */
  ownership: "managed" | "foreign";
  risk: "safe" | "requires-confirmation";
  target: InstallTarget;
  mode: "file" | "block";
  blockId?: string;
}

export interface PlanOptions {
  /** Regenerate managed files whose content changed. */
  updateManaged: boolean;
  /** Only ever true with an explicit user override; protects unknown local files. */
  allowForeignOverwrite?: boolean;
}

export interface FileCandidate {
  file: string;
  content: string;
  target: InstallTarget;
  mode?: "file" | "block";
  blockId?: string;
}

const FOREIGN_OVERWRITE_BLOCK = "refusing to overwrite a file Steward does not own";

function normalize(file: string): string {
  return path.normalize(file).replace(/\\/g, "/");
}

/**
 * Classify one candidate write against current filesystem state.
 * Ownership is decided by the Steward provenance marker, never by path.
 */
export function classifyFile(
  candidate: FileCandidate,
  existingContent: string | null,
  opts: PlanOptions
): FileAction {
  const base = {
    file: normalize(candidate.file),
    target: candidate.target,
    mode: candidate.mode ?? "file",
    blockId: candidate.blockId,
  };
  // Block-mode writes are additive merges into the host doc (markers delimit
  // the managed region; everything else is preserved). They are always safe:
  // the engine backs up the host file and uninstall strips only the block.
  if ((candidate.mode ?? "file") === "block") {
    if (existingContent === candidate.content) {
      return {
        ...base,
        kind: "skip",
        content: candidate.content,
        reason: "managed block already up to date",
        ownership: "managed",
        risk: "safe",
      };
    }
    return {
      ...base,
      kind: existingContent === null ? "create" : "overwrite",
      content: candidate.content,
      reason:
        existingContent === null
          ? "new file with managed block"
          : "managed block added/updated in existing doc (additive merge)",
      ownership: "managed",
      risk: "safe",
    };
  }
  if (existingContent === null) {
    return {
      ...base,
      kind: "create",
      content: candidate.content,
      reason: "new file",
      ownership: "managed",
      risk: "safe",
    };
  }
  if (existingContent === candidate.content) {
    return {
      ...base,
      kind: "skip",
      content: candidate.content,
      reason: "already up to date",
      ownership: "managed",
      risk: "safe",
    };
  }
  const isManaged = existingContent.includes("Generated by Steward");
  if (isManaged) {
    return opts.updateManaged
      ? {
          ...base,
          kind: "overwrite",
          content: candidate.content,
          reason: "managed file, content changed",
          ownership: "managed",
          risk: "safe",
        }
      : {
          ...base,
          kind: "skip",
          content: candidate.content,
          reason: "managed file changed; updateManaged=false",
          ownership: "managed",
          risk: "safe",
        };
  }
  if (opts.allowForeignOverwrite === true) {
    return {
      ...base,
      kind: "overwrite",
      content: candidate.content,
      reason: "foreign file, explicit overwrite authorized",
      ownership: "foreign",
      risk: "requires-confirmation",
    };
  }
  return {
    ...base,
    kind: "skip",
    content: candidate.content,
    reason: FOREIGN_OVERWRITE_BLOCK,
    ownership: "foreign",
    risk: "requires-confirmation",
  };
}
